version: '3'
services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - '5173:5173'

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - .:/usr/share/nginx/html/website # Copy
